import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import Report from "../models/Report.js";
import Project from "../models/Project.js";
import ComplianceCheck from "../models/ComplianceCheck.js";
import File from "../models/File.js";
import { env } from "../config/env.js";

const GREEN = "#154212";
const GREEN_LIGHT = "#e8f0e7";
const GREEN_MID = "#2d5a27";
const ZINC_900 = "#18181b";
const ZINC_700 = "#3f3f46";
const ZINC_500 = "#71717a";
const ZINC_300 = "#d4d4d8";
const ZINC_100 = "#f4f4f5";
const RED = "#b91c1c";
const RED_LIGHT = "#fef2f2";
const AMBER = "#d97706";
const AMBER_LIGHT = "#fffbeb";
const WHITE = "#ffffff";

const ensureDir = (dir) => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
};

const drawRect = (doc, x, y, w, h, color) => {
  doc.save().rect(x, y, w, h).fill(color).restore();
};

const drawLine = (doc, x1, y1, x2, y2, color = ZINC_300, width = 0.5) => {
  doc.save().moveTo(x1, y1).lineTo(x2, y2).strokeColor(color).lineWidth(width).stroke().restore();
};

const pageWidth = 595;
const pageHeight = 842;
const marginL = 45;
const marginR = 45;
const contentWidth = pageWidth - marginL - marginR;

const drawHeader = (doc, reportTitle, projectName, generatedDate, pageNum) => {
  drawRect(doc, 0, 0, pageWidth, 52, GREEN);
  doc.save()
    .fontSize(16)
    .font("Helvetica-Bold")
    .fillColor(WHITE)
    .text("CivilOS", marginL, 16, { continued: true })
    .fontSize(9)
    .font("Helvetica")
    .fillColor("#a7f3d0")
    .text("  Infrastructure Regulations Terminal", { continued: false });

  doc.fontSize(7.5)
    .font("Helvetica")
    .fillColor("#6ee7b7")
    .text(`${reportTitle.toUpperCase()}`, marginL, 36);

  doc.fontSize(7.5)
    .fillColor("#6ee7b7")
    .text(`Page ${pageNum}`, 0, 36, { align: "right", width: pageWidth - marginR });
  doc.restore();

  drawRect(doc, 0, 52, pageWidth, 3, GREEN_MID);
};

const drawFooter = (doc, projectName, date) => {
  const y = pageHeight - 38;
  drawRect(doc, 0, y, pageWidth, 38, ZINC_100);
  drawLine(doc, 0, y, pageWidth, y, ZINC_300, 0.5);

  doc.save()
    .fontSize(7)
    .font("Helvetica")
    .fillColor(ZINC_500)
    .text(`Project: ${projectName}`, marginL, y + 8)
    .text(`Generated: ${date}`, marginL, y + 20);

  doc.fontSize(7)
    .fillColor(ZINC_500)
    .text("Generated by CivilOS — AI-Native Structural Compliance Platform", 0, y + 8, { align: "right", width: pageWidth - marginR })
    .text("Bureau of Indian Standards · IS 456 · IS 800 · IS 1893", 0, y + 20, { align: "right", width: pageWidth - marginR });
  doc.restore();
};

const drawCoverPage = (doc, project, report, date) => {
  drawRect(doc, 0, 0, pageWidth, pageHeight, WHITE);
  drawRect(doc, 0, 0, pageWidth, 220, GREEN);
  drawRect(doc, 0, 220, pageWidth, 4, GREEN_MID);

  doc.save()
    .fontSize(28)
    .font("Helvetica-Bold")
    .fillColor(WHITE)
    .text("CivilOS", marginL, 50);

  doc.fontSize(10)
    .font("Helvetica")
    .fillColor("#a7f3d0")
    .text("Infrastructure Regulations Terminal", marginL, 86);

  doc.fontSize(7)
    .fillColor("#6ee7b7")
    .text("BUREAU OF INDIAN STANDARDS CODE COMPLIANCE PLATFORM", marginL, 108);

  drawLine(doc, marginL, 124, pageWidth - marginR, 124, "#2d5a27", 0.6);

  doc.fontSize(18)
    .font("Helvetica-Bold")
    .fillColor(WHITE)
    .text(report.title, marginL, 136, { width: contentWidth });

  doc.fontSize(9)
    .font("Helvetica")
    .fillColor("#86efac")
    .text(report.type.toUpperCase() + " REPORT", marginL, 196);
  doc.restore();

  const metaY = 260;
  const col1 = marginL;
  const col2 = marginL + 260;

  const metaItems = [
    ["PROJECT NAME", project?.name || "N/A"],
    ["PROJECT TYPE", project?.type?.toUpperCase() || "N/A"],
    ["PROJECT STATUS", project?.status?.toUpperCase() || "ACTIVE"],
    ["REPORT TYPE", report.type.toUpperCase()],
    ["GENERATED DATE", date],
    ["STANDARD REFERENCES", "IS 456:2000 · IS 800:2007 · IS 1893:2016"],
  ];

  metaItems.forEach((item, i) => {
    const x = i % 2 === 0 ? col1 : col2;
    const y = metaY + Math.floor(i / 2) * 52;

    drawRect(doc, x, y, 230, 42, ZINC_100);
    drawLine(doc, x, y, x, y + 42, GREEN, 2.5);

    doc.save()
      .fontSize(7)
      .font("Helvetica-Bold")
      .fillColor(ZINC_500)
      .text(item[0], x + 10, y + 8);

    doc.fontSize(9)
      .font("Helvetica-Bold")
      .fillColor(ZINC_900)
      .text(item[1], x + 10, y + 22, { width: 210 });
    doc.restore();
  });

  const infoY = metaY + 168;
  drawRect(doc, marginL, infoY, contentWidth, 60, GREEN_LIGHT);
  drawLine(doc, marginL, infoY, marginL, infoY + 60, GREEN, 3);

  doc.save()
    .fontSize(7.5)
    .font("Helvetica-Bold")
    .fillColor(GREEN)
    .text("ABOUT THIS REPORT", marginL + 12, infoY + 10);

  doc.fontSize(8.5)
    .font("Helvetica")
    .fillColor(ZINC_700)
    .text(
      "This document is an AI-generated structural compliance report produced by CivilOS. It cross-references uploaded structural drawings, PDF reports, and STAAD analysis data against Bureau of Indian Standards codes including IS 456:2000, IS 800:2007, and IS 1893:2016.",
      marginL + 12, infoY + 24, { width: contentWidth - 24 }
    );
  doc.restore();

  const badgeY = infoY + 82;
  ["IS 456:2000", "IS 800:2007", "IS 1893:2016", "IS 2911:2010", "IS 875"].forEach((code, i) => {
    const bx = marginL + i * 100;
    drawRect(doc, bx, badgeY, 88, 22, GREEN);
    doc.save()
      .fontSize(7)
      .font("Helvetica-Bold")
      .fillColor(WHITE)
      .text(code, bx, badgeY + 7, { width: 88, align: "center" });
    doc.restore();
  });

  const dividerY = pageHeight - 120;
  drawLine(doc, marginL, dividerY, pageWidth - marginR, dividerY, ZINC_300);

  doc.save()
    .fontSize(7)
    .font("Helvetica")
    .fillColor(ZINC_500)
    .text("CONFIDENTIAL — For project use only. All calculations reference Bureau of Indian Standards publications.", marginL, dividerY + 12, { width: contentWidth, align: "center" })
    .text(`CivilOS Platform · v1.0 · ${date}`, marginL, dividerY + 26, { width: contentWidth, align: "center" });
  doc.restore();
};

const drawSectionHeader = (doc, title, subtitle = "") => {
  const y = doc.y;
  drawRect(doc, marginL, y, contentWidth, 32, GREEN_LIGHT);
  drawLine(doc, marginL, y, marginL, y + 32, GREEN, 3);

  doc.save()
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor(GREEN)
    .text(title, marginL + 12, y + 8);

  if (subtitle) {
    doc.fontSize(7.5)
      .font("Helvetica")
      .fillColor(ZINC_500)
      .text(subtitle, marginL + 12, y + 22);
  }
  doc.restore();
  doc.y = y + 40;
};

const drawStatCard = (doc, x, y, w, h, label, value, color = GREEN) => {
  drawRect(doc, x, y, w, h, WHITE);
  doc.save().rect(x, y, w, h).strokeColor(ZINC_300).lineWidth(0.5).stroke().restore();
  drawLine(doc, x, y, x, y + h, color, 2.5);

  doc.save()
    .fontSize(7)
    .font("Helvetica-Bold")
    .fillColor(ZINC_500)
    .text(label.toUpperCase(), x + 8, y + 8, { width: w - 16 });

  doc.fontSize(14)
    .font("Helvetica-Bold")
    .fillColor(color)
    .text(value, x + 8, y + 22, { width: w - 16 });
  doc.restore();
};

const drawTableHeader = (doc, columns, y) => {
  drawRect(doc, marginL, y, contentWidth, 22, ZINC_900);
  let x = marginL;
  columns.forEach((col) => {
    doc.save()
      .fontSize(7)
      .font("Helvetica-Bold")
      .fillColor(WHITE)
      .text(col.label.toUpperCase(), x + 6, y + 7, { width: col.width - 12 });
    doc.restore();
    x += col.width;
  });
  return y + 22;
};

const drawTableRow = (doc, columns, row, y, isAlt, statusColor) => {
  const rowH = 22;
  const bg = statusColor ? (statusColor === "pass" ? "#f0fdf4" : statusColor === "fail" ? "#fef2f2" : AMBER_LIGHT) : (isAlt ? ZINC_100 : WHITE);
  drawRect(doc, marginL, y, contentWidth, rowH, bg);
  drawLine(doc, marginL, y + rowH, marginL + contentWidth, y + rowH, ZINC_300, 0.3);

  let x = marginL;
  columns.forEach((col, i) => {
    const val = row[i] ?? "—";
    const textColor = i === 0 ? ZINC_900 : ZINC_700;
    doc.save()
      .fontSize(8)
      .font(i === 0 ? "Helvetica-Bold" : "Helvetica")
      .fillColor(textColor)
      .text(String(val), x + 6, y + 7, { width: col.width - 12, ellipsis: true });
    doc.restore();
    x += col.width;
  });
  return y + rowH;
};

const writeComplianceSection = async (doc, projectId, project, date, pageTracker) => {
  const checks = await ComplianceCheck.findAll({
    where: { project_id: projectId },
    order: [["created_at", "DESC"]],
    limit: 1,
  });

  const latestCheck = checks[0];

  doc.addPage();
  pageTracker.page++;
  drawHeader(doc, "Compliance Report", project?.name, date, pageTracker.page);
  doc.y = 72;

  drawSectionHeader(doc, "Compliance Audit Summary", `IS Code verification results — ${date}`);
  doc.moveDown(0.5);

  if (!latestCheck) {
    doc.fontSize(9).font("Helvetica").fillColor(ZINC_500).text("No compliance checks found. Run a compliance audit from the CivilOS platform.", marginL, doc.y);
    drawFooter(doc, project?.name, date);
    return;
  }

  const totalChecks = latestCheck.total_checks || 0;
  const passedChecks = latestCheck.passed_checks || 0;
  const failedChecks = latestCheck.failed_checks || 0;
  const integrityPct = totalChecks > 0 ? Math.round((passedChecks / totalChecks) * 100) : 0;

  const cardW = (contentWidth - 12) / 4;
  const cardY = doc.y;
  drawStatCard(doc, marginL, cardY, cardW, 52, "Integrity Score", `${integrityPct}%`, integrityPct >= 80 ? GREEN : RED);
  drawStatCard(doc, marginL + cardW + 4, cardY, cardW, 52, "Total Checks", `${totalChecks}`, ZINC_700);
  drawStatCard(doc, marginL + (cardW + 4) * 2, cardY, cardW, 52, "Passed", `${passedChecks}`, GREEN);
  drawStatCard(doc, marginL + (cardW + 4) * 3, cardY, cardW, 52, "Failed", `${failedChecks}`, failedChecks > 0 ? RED : GREEN);
  doc.y = cardY + 64;

  drawRect(doc, marginL, doc.y, contentWidth, 30, latestCheck.status === "passed" ? "#f0fdf4" : RED_LIGHT);
  drawLine(doc, marginL, doc.y, marginL, doc.y + 30, latestCheck.status === "passed" ? GREEN : RED, 3);

  doc.save()
    .fontSize(8)
    .font("Helvetica-Bold")
    .fillColor(latestCheck.status === "passed" ? GREEN : RED)
    .text(`AUDIT VERDICT: ${latestCheck.status.toUpperCase()}`, marginL + 12, doc.y + 6);

  doc.fontSize(8)
    .font("Helvetica")
    .fillColor(ZINC_700)
    .text(`IS Code: ${latestCheck.is_code} · Member Type: ${latestCheck.member_type?.toUpperCase()} · ${latestCheck.summary || ""}`, marginL + 12, doc.y + 18);
  doc.restore();
  doc.y = doc.y + 42;

  const results = (latestCheck.results || []).filter(r => r.clause !== "N/A");

  if (results.length > 0) {
    doc.moveDown(0.5);
    drawSectionHeader(doc, "Member Check Results", `${results.length} member(s) evaluated against IS code clauses`);

    const cols = [
      { label: "Member ID", width: 80 },
      { label: "Check Type", width: 80 },
      { label: "IS Clause", width: 140 },
      { label: "Vu (kN)", width: 60 },
      { label: "Vc (kN)", width: 60 },
      { label: "Status", width: 85 },
    ];

    let tableY = drawTableHeader(doc, cols, doc.y);

    results.forEach((r, i) => {
      if (tableY > pageHeight - 80) {
        drawFooter(doc, project?.name, date);
        doc.addPage();
        pageTracker.page++;
        drawHeader(doc, "Compliance Report", project?.name, date, pageTracker.page);
        tableY = 80;
        tableY = drawTableHeader(doc, cols, tableY);
      }

      const rowData = [
        r.member_id || r.member_label || "—",
        r.check || "shear",
        r.clause || "—",
        r.vu !== undefined ? r.vu.toFixed(1) : "—",
        r.vc !== undefined ? r.vc.toFixed(1) : "—",
        r.status?.toUpperCase() || "—",
      ];
      tableY = drawTableRow(doc, cols, rowData, tableY, i % 2 === 1, r.status);
    });

    doc.y = tableY + 16;

    const failedResults = results.filter(r => r.status === "fail");
    if (failedResults.length > 0) {
      doc.moveDown(0.5);
      drawSectionHeader(doc, "Violation Details & Remediation", `${failedResults.length} critical violation(s) require attention`);

      failedResults.forEach((r, i) => {
        if (doc.y > pageHeight - 140) {
          drawFooter(doc, project?.name, date);
          doc.addPage();
          pageTracker.page++;
          drawHeader(doc, "Compliance Report", project?.name, date, pageTracker.page);
          doc.y = 72;
        }

        const blockY = doc.y;
        drawRect(doc, marginL, blockY, contentWidth, 88, RED_LIGHT);
        doc.save().rect(marginL, blockY, contentWidth, 88).strokeColor("#fca5a5").lineWidth(0.5).stroke().restore();
        drawLine(doc, marginL, blockY, marginL, blockY + 88, RED, 3);

        doc.save()
          .fontSize(8)
          .font("Helvetica-Bold")
          .fillColor(RED)
          .text(`VIOLATION ${i + 1} — ${r.member_id || "Member"} — ${r.clause}`, marginL + 12, blockY + 8);

        doc.fontSize(8)
          .font("Helvetica")
          .fillColor(ZINC_700)
          .text(`Reason: ${r.reason || "Shear demand exceeds capacity"}`, marginL + 12, blockY + 24, { width: contentWidth - 24 });

        if (r.vu !== undefined && r.vc !== undefined) {
          doc.fontSize(8)
            .fillColor(RED)
            .text(`Vu = ${r.vu} kN  >  Vc = ${r.vc} kN  (Excess: +${(r.vu - r.vc).toFixed(1)} kN)`, marginL + 12, blockY + 40);
        }

        if (r.suggestion) {
          doc.fontSize(8)
            .font("Helvetica-Bold")
            .fillColor("#1d4ed8")
            .text(`Recommendation: `, marginL + 12, blockY + 56, { continued: true })
            .font("Helvetica")
            .fillColor(ZINC_700)
            .text(r.suggestion, { continued: false, width: contentWidth - 24 });
        }

        doc.fontSize(7)
          .font("Helvetica")
          .fillColor(ZINC_500)
          .text(`IS Code Reference: ${r.clause} — Bureau of Indian Standards`, marginL + 12, blockY + 72);
        doc.restore();

        doc.y = blockY + 100;
      });
    }

    const passedResults = results.filter(r => r.status === "pass");
    if (passedResults.length > 0) {
      if (doc.y > pageHeight - 100) {
        drawFooter(doc, project?.name, date);
        doc.addPage();
        pageTracker.page++;
        drawHeader(doc, "Compliance Report", project?.name, date, pageTracker.page);
        doc.y = 72;
      }

      drawSectionHeader(doc, "Compliant Members", `${passedResults.length} member(s) passed all IS code checks`);

      passedResults.forEach((r, i) => {
        const blockY = doc.y;
        drawRect(doc, marginL, blockY, contentWidth, 44, "#f0fdf4");
        doc.save().rect(marginL, blockY, contentWidth, 44).strokeColor("#86efac").lineWidth(0.5).stroke().restore();
        drawLine(doc, marginL, blockY, marginL, blockY + 44, GREEN, 3);

        doc.save()
          .fontSize(8)
          .font("Helvetica-Bold")
          .fillColor(GREEN)
          .text(`✓ PASS — ${r.member_id || "Member"} — ${r.clause}`, marginL + 12, blockY + 8);

        doc.fontSize(8)
          .font("Helvetica")
          .fillColor(ZINC_700)
          .text(`${r.reason || "All checks passed"}`, marginL + 12, blockY + 24, { width: contentWidth - 24 });
        doc.restore();

        doc.y = blockY + 56;
      });
    }
  } else {
    doc.fontSize(9).font("Helvetica").fillColor(ZINC_500)
      .text("No member-level results found. Upload structural documents and run compliance audit.", marginL, doc.y);
  }

  drawFooter(doc, project?.name, date);
};

const writeSummarySection = async (doc, projectId, project, date, pageTracker) => {
  doc.addPage();
  pageTracker.page++;
  drawHeader(doc, "Project Summary", project?.name, date, pageTracker.page);
  doc.y = 72;

  drawSectionHeader(doc, "Project Overview", "General project information and metadata");
  doc.moveDown(0.5);

  const fields = [
    ["Project Name", project?.name || "N/A"],
    ["Project Type", project?.type || "N/A"],
    ["Status", project?.status || "active"],
    ["Description", project?.description || "No description provided"],
    ["Created At", new Date(project?.createdAt).toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })],
  ];

  fields.forEach((f, i) => {
    const rowY = doc.y;
    drawRect(doc, marginL, rowY, contentWidth, 22, i % 2 === 0 ? WHITE : ZINC_100);
    drawLine(doc, marginL, rowY + 22, marginL + contentWidth, rowY + 22, ZINC_300, 0.3);

    doc.save()
      .fontSize(8)
      .font("Helvetica-Bold")
      .fillColor(ZINC_500)
      .text(f[0], marginL + 8, rowY + 7, { width: 120 });

    doc.fontSize(8)
      .font("Helvetica")
      .fillColor(ZINC_900)
      .text(f[1], marginL + 140, rowY + 7, { width: contentWidth - 148 });
    doc.restore();
    doc.y = rowY + 22;
  });

  doc.moveDown(1);
  drawSectionHeader(doc, "IS Code Coverage", "Standards referenced in this project");
  doc.moveDown(0.5);

  const standards = [
    ["IS 456:2000", "Plain and Reinforced Concrete — Code of Practice", "Concrete Design"],
    ["IS 800:2007", "General Construction in Steel — Code of Practice", "Steel Design"],
    ["IS 1893:2016", "Criteria for Earthquake Resistant Design of Structures", "Seismic Design"],
    ["IS 2911:2010", "Design and Construction of Pile Foundations", "Foundation Design"],
    ["IS 875:1987", "Code of Practice for Design Loads for Buildings", "Load Standards"],
    ["IS 13920:2016", "Ductile Design and Detailing of RC Structures", "Seismic Detailing"],
  ];

  const stdCols = [
    { label: "IS Code", width: 100 },
    { label: "Description", width: 270 },
    { label: "Category", width: 135 },
  ];

  let tableY = drawTableHeader(doc, stdCols, doc.y);
  standards.forEach((s, i) => {
    tableY = drawTableRow(doc, stdCols, s, tableY, i % 2 === 1, null);
  });

  doc.y = tableY + 16;
  drawFooter(doc, project?.name, date);
};

export const generatePDF = async ({ reportId, projectId, type }) => {
  const report = await Report.findByPk(reportId);
  const project = await Project.findByPk(projectId);

  const outputDir = path.join(env.UPLOAD_DIR, projectId, "reports");
  ensureDir(outputDir);
  const outputPath = path.join(outputDir, `${reportId}.pdf`);

  const doc = new PDFDocument({
    size: "A4",
    margin: 0,
    autoFirstPage: false,
    info: {
      Title: report.title,
      Author: "CivilOS Platform",
      Subject: "Structural Compliance Report",
      Keywords: "IS 456, IS 800, IS 1893, structural compliance, CivilOS",
    },
  });

  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  const date = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });
  const pageTracker = { page: 0 };

  doc.addPage();
  pageTracker.page = 1;
  drawCoverPage(doc, project, report, date);

  if (type === "compliance") {
    await writeComplianceSection(doc, projectId, project, date, pageTracker);
  } else {
    await writeSummarySection(doc, projectId, project, date, pageTracker);
  }

  if (type === "compliance") {
    await writeSummarySection(doc, projectId, project, date, pageTracker);
  }

  doc.end();

  await new Promise((resolve, reject) => {
    stream.on("finish", resolve);
    stream.on("error", reject);
  });

  return outputPath;
};